# Generated by Django 6.1 on 2026-08-23 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_recipe", "0002_recipe_recipeingredient_recipe_ingredients_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Step",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("instruction", models.TextField()),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="steps",
                        to="app_recipe.recipe",
                    ),
                ),
            ],
            options={
                "ordering": ["recipe", "order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("recipe", "order"), name="unique_step_order"
                    )
                ],
            },
        ),
    ]
